Voter:
  best_accuracy: 95.0
  best_param: 0.9
dct:
  best_accuracy: 97.5
  best_param: 0.8
dft:
  best_accuracy: 97.5
  best_param: 0.9
hist:
  best_accuracy: 100.0
  best_param: 0.7
scaler:
  best_accuracy: 83.75
  best_param: 0.8
sliding_window:
  best_accuracy: 85.0
  best_param: 0.8
